#############################################################################
# Makefile for building findw_t
# Generated by tmake at 13:40, 2003/04/09
#     Project: findw
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CFLAGS	=	-O -Wall
INCPATH	=	
LINK	=	gcc
LFLAGS	=	-Wl,-subsystem,-strip-all
LIBS	=	
UIC	=	
OSUFFIX =	.o

include_dirs := include
source_dirs  := src
objects_dirs := bin

####### Files

HEADERS =	${include_dirs}/findw.h \
		${include_dirs}/platform.h
SOURCES =	${source_dirs}/analiz.c \
		${source_dirs}/bintree.c \
		${source_dirs}/dict.c \
		${source_dirs}/findw.c \
		${source_dirs}/hash.c \
		${source_dirs}/wfiles.c \
		${source_dirs}/list.c \
		${source_dirs}/conv.c
OBJECTS =	${objects_dirs}/analiz$(OSUFFIX) \
		${objects_dirs}/bintree$(OSUFFIX) \
		${objects_dirs}/dict$(OSUFFIX) \
		${objects_dirs}/findw$(OSUFFIX) \
		${objects_dirs}/hash$(OSUFFIX) \
		${objects_dirs}/wfiles$(OSUFFIX) \
		${objects_dirs}/list$(OSUFFIX) \
		${objects_dirs}/conv$(OSUFFIX) 
UICDECLS =	
TARGET	=	findw_t.exe

####### Build rules


all: $(TARGET)

$(TARGET): obj_dirs $(UICDECLS) $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)

obj_dirs :
	mkdir -p bin

clean:
	-rm -f $(OBJECTS) $(TARGET)
	-rm -f *~ core

####### Compile

${objects_dirs}/%.o : ${source_dirs}/%.c
	gcc -o $@ -c $< ${CFLAGS}
