#!/bin/bash

while true; do
  ./findw_t.exe -c -l -e
  if [ -e "2log" ]; then
    echo new pass
    mv "2log" "1hrefs"
  else 
    if [ -e "1hrefs" ]; then
      rm "1hrefs"
    fi
    break;
  fi
done
echo next generation
./findw_t.exe -d $1 -e
