#############################################################################
# Makefile for building findw_t
# Generated by tmake at 13:40, 2003/04/09
#     Project: findw
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CFLAGS	=	-O
INCPATH	=	
LINK	=	gcc
LFLAGS	=	-Wl,-subsystem,-strip-all
LIBS	=	
UIC	=	
OSUFFIX =	.o

####### Files

HEADERS =	findw.h \
		fnmatch.h \
		platform.h
SOURCES =	analiz.c \
		bintree.c \
		dict.c \
		findw.c \
		hash.c \
		wfiles.c \
		list.c \
		conv.c
OBJECTS =	analiz$(OSUFFIX) \
		bintree$(OSUFFIX) \
		dict$(OSUFFIX) \
		findw$(OSUFFIX) \
		hash$(OSUFFIX) \
		wfiles$(OSUFFIX) \
		list$(OSUFFIX) \
		conv$(OSUFFIX) 
UICDECLS =	
TARGET	=	findw_t.exe

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)



clean:
	-rm -f $(OBJECTS) $(TARGET)
	-rm -f *~ core

####### Compile

analiz$(OSUFFIX): analiz.c \
		findw.h

bintree$(OSUFFIX): bintree.c \
		findw.h

dict$(OSUFFIX): dict.c \
		platform.h \
		findw.h

findw$(OSUFFIX): findw.c \
		findw.h

hash$(OSUFFIX): hash.c \
		findw.h

wfiles$(OSUFFIX): wfiles.c \
		findw.h

list$(OSUFFIX): list.c \
		findw.h

conv$(OSUFFIX): conv.c
